language: node_js
node_js:
  - "node"
  - "10"
install:
  - npm install
script:
  - npm run test:coveralls
after_success:
- ./node_modules/.bin/jscoverage lib lib-cov
- ./node_modules/.bin/mocha YOUR_TESTS/**.js -R mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
